#!/bin/sh

wlr-randr --output DP-2 --pos -1920,-1080 --scale 0.75

riverctl keyboard-layout "us(colemak)"

riverctl spawn "foot --server"
riverctl map normal Super T spawn footclient
riverctl map normal Super W spawn firefox
riverctl spawn "light -I"

riverctl map normal Super+Shift Return zoom
riverctl map normal Super+Shift F toggle-fullscreen
riverctl map normal Super+Shift Space toggle-float
riverctl map normal Super+Shift C close
riverctl map normal Super+Shift E exit

# riverctl map normal Super Up focus-view up
# riverctl map normal Super Down focus-view down
# riverctl map normal Super Left focus-view left
# riverctl map normal Super Right focus-view right
# riverctl map normal Super+Shift Up swap up
# riverctl map normal Super+Shift Down swap down
# riverctl map normal Super+Shift Left swap left
# riverctl map normal Super+Shift Right swap right
riverctl map normal Super Up focus-view previous
riverctl map normal Super Down focus-view next
riverctl map normal Super+Shift Up swap previous
riverctl map normal Super+Shift Down swap next

riverctl map normal Super Period focus-output next
riverctl map normal Super Comma focus-output previous
riverctl map normal Super+Shift Period send-to-output next
riverctl map normal Super+Shift Comma send-to-output previous

riverctl map normal Super+Control Left send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal Super+Control Right send-layout-cmd rivertile "main-ratio +0.05"

riverctl map normal Super+Control+Shift Up send-layout-cmd rivertile "main-location top"
riverctl map normal Super+Control+Shift Down send-layout-cmd rivertile "main-location bottom"
riverctl map normal Super+Control+Shift Left send-layout-cmd rivertile "main-location left"
riverctl map normal Super+Control+Shift Right send-layout-cmd rivertile "main-location right"

riverctl map normal Super+Alt Up move up 100
riverctl map normal Super+Alt Down move down 100
riverctl map normal Super+Alt Left move left 100
riverctl map normal Super+Alt Right move right 100
riverctl map normal Super+Alt+Control Up snap up
riverctl map normal Super+Alt+Control Down snap down
riverctl map normal Super+Alt+Control Left snap left
riverctl map normal Super+Alt+Control Right snap right
riverctl map normal Super+Alt+Shift Up resize vertical -100
riverctl map normal Super+Alt+Shift Down resize vertical 100
riverctl map normal Super+Alt+Shift Left resize horizontal -100
riverctl map normal Super+Alt+Shift Right resize horizontal 100

riverctl map-pointer normal Super BTN_LEFT move-view
riverctl map-pointer normal Super BTN_RIGHT resize-view
riverctl map-pointer normal Super BTN_MIDDLE toggle-float

for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))

    riverctl map normal Super $i set-focused-tags $tags
    riverctl map normal Super+Shift $i set-view-tags $tags
    riverctl map normal Super+Control $i toggle-focused-tags $tags
    riverctl map normal Super+Shift+Control $i toggle-view-tags $tags
done

all_tags=$(((1 << 32) - 1))
riverctl map normal Super 0 set-focused-tags $all_tags
riverctl map normal Super+Shift 0 set-view-tags $all_tags

for mode in normal locked
do
    riverctl map $mode None XF86Eject spawn "eject -T"

    riverctl map $mode None XF86AudioRaiseVolume spawn "pamixer -i 5"
    riverctl map $mode None XF86AudioLowerVolume spawn "pamixer -d 5"
    riverctl map $mode None XF86AudioMute spawn "pamixer --toggle-mute"

    riverctl map $mode None XF86AudioMedia spawn "playerctl play-pause"
    riverctl map $mode None XF86AudioPlay spawn "playerctl play-pause"
    riverctl map $mode None XF86AudioPrev spawn "playerctl previous"
    riverctl map $mode None XF86AudioNext spawn "playerctl next"

    riverctl map $mode None XF86MonBrightnessUp spawn "light -A 5"
    riverctl map $mode None XF86MonBrightnessDown spawn "light -U 5"
done

riverctl background-color 0x000000
riverctl border-color-focused 0x93a1a1
riverctl border-color-unfocused 0x586e75

riverctl spawn "rivertile -view-padding 0"
riverctl default-layout rivertile

